/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "brand-orange": "#EF7D00",
        "brand-gold": "#A28034",
        "brand-yellow": "#FEC800",
        "brand-red": "#F7003C",
        "brand-blue": "#0071BB",
        "brand-cyan": "#00B7D9",
        "brand-lightblue": "#9FD7E5",
        "brand-green": "#69B75E",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-secondary-container": "#00486a",
        "primary-container": "#002f6c",
        "tertiary-fixed": "#e2e2e2",
        "surface-tint": "#3c5d9c",
        "on-error": "#ffffff",
        "outline-variant": "#c4c6d2",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed-variant": "#004b6f",
        "secondary-fixed": "#c9e6ff",
        "on-tertiary-fixed-variant": "#454747",
        "error": "#ba1a1a",
        "tertiary": "#1b1d1d",
        "surface-variant": "#e4e2e1",
        "secondary-container": "#45baff",
        "background": "#fbf9f8",
        "primary-fixed": "#d8e2ff",
        "on-surface-variant": "#434750",
        "on-background": "#1b1c1c",
        "surface": "#fbf9f8",
        "inverse-on-surface": "#f3f0f0",
        "on-tertiary-container": "#999a9a",
        "surface-bright": "#fbf9f8",
        "on-primary": "#ffffff",
        "outline": "#747781",
        "inverse-primary": "#aec6ff",
        "tertiary-container": "#303232",
        "on-primary-fixed-variant": "#224583",
        "secondary-fixed-dim": "#8bceff",
        "secondary": "#006492",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001a42",
        "surface-container-high": "#eae8e7",
        "on-primary-container": "#7999dc",
        "error-container": "#ffdad6",
        "on-surface": "#1b1c1c",
        "primary-fixed-dim": "#aec6ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001e2f",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e4e2e1",
        "surface-container": "#f0eded",
        "primary": "#001b44",
        "inverse-surface": "#303030",
        "surface-dim": "#dcd9d9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1200px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "gutter": "24px",
        "base": "8px",
        "stack-md": "16px"
      },
      fontFamily: {
        sans: ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "body-lg": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "headline-lg": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "label-md": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "headline-xl": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "body-md": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "body-sm": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "headline-md": ["Metropolis", "Poppins", "Inter", "sans-serif"],
        "label-sm": ["Metropolis", "Poppins", "Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
